# Generated by Django 4.2.9 on 2024-01-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='sku',
            field=models.CharField(default='N/D', max_length=100),
        ),
    ]
